# Generated by Django 5.1.7 on 2025-08-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('api_base_url', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=256, null=True)),
                ('fb_page_id', models.CharField(blank=True, max_length=64, null=True)),
                ('fb_page_access_token', models.TextField(blank=True, null=True)),
                ('waba_phone_id', models.CharField(blank=True, max_length=64, null=True)),
                ('waba_access_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
