# Generated by Django 5.1.4 on 2025-09-10 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='api_base_url',
            new_name='db_url',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='fb_page_access_token',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='fb_page_id',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='waba_access_token',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='waba_phone_id',
        ),
        migrations.AddField(
            model_name='tenant',
            name='rest_api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='api_key',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
