# Generated by Django 5.1.4 on 2025-09-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_api_base_url_tenant_db_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='rest_api_url',
        ),
    ]
