# Generated by Django 5.1.4 on 2025-09-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_tenant_rest_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='rest_api',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
